version: "3"

networks:
  default:
    external: true
    name: ${INTERNAL_NETWORK}

services:
  unittest:
    container_name: ${UNITTEST_CONTAINER}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      network: host
    command: "python3 -m pytest -s ${UNITTEST_TARGET:-}"
    init: true
    networks:
      - default
    volumes:
      - ..:/app
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      PYTHONWARNINGS: ${SERVER_PRINT_WARNING:-ignore}

      SERVER_TIMEZONE: ${SERVER_TIMEZONE:-Asia/Seoul}
      SERVER_ENGINE_DEVICES: ${SERVER_ENGINE_DEVICES}
      SERVER_WORKER_NUM: ${SERVER_WORKER_NUM}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
